//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Random/Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player"",
    ""maps"": [
        {
            ""name"": ""inter"",
            ""id"": ""7944e92f-9f33-4c11-bdd1-0b930584937a"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""4fd40c6a-606d-4b41-b4e4-203a3a7e03e4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""38c9b04b-2a05-416c-9cdd-8a602528942b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Flying car"",
            ""id"": ""7c3ddac9-8f9c-4bcd-ab4a-b94406678adf"",
            ""actions"": [
                {
                    ""name"": ""Driving"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f564e338-1912-4c16-989f-3a091fa8ee7b"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": ""Press,Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Braking"",
                    ""type"": ""Button"",
                    ""id"": ""883fbc82-ad19-4829-b380-d68bfcb5a2d8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""6c7e4dc5-9f71-4f54-bee2-6f32440be71a"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector3"",
                    ""groups"": """",
                    ""action"": ""Driving"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Forward"",
                    ""id"": ""a8579c4c-2bda-41d9-9cbc-9bf2ebcb1238"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Driving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Backward"",
                    ""id"": ""cf873b31-a08f-4fd7-be94-619ac4cabd16"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Driving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bae256dd-258a-4366-a80f-c262d5fc7fb1"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Driving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""345c6200-ffb7-41f0-8860-a6a7edd1a4f9"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Driving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""30f3668b-2a1e-4fe2-b544-43d71ed7dc83"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Driving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""27700f36-5b49-494c-9e4b-f7ce6d499197"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Driving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""37fd1c06-b88a-44cc-aba6-0aec1e12af15"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Braking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // inter
        m_inter = asset.FindActionMap("inter", throwIfNotFound: true);
        m_inter_Interact = m_inter.FindAction("Interact", throwIfNotFound: true);
        // Flying car
        m_Flyingcar = asset.FindActionMap("Flying car", throwIfNotFound: true);
        m_Flyingcar_Driving = m_Flyingcar.FindAction("Driving", throwIfNotFound: true);
        m_Flyingcar_Braking = m_Flyingcar.FindAction("Braking", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // inter
    private readonly InputActionMap m_inter;
    private List<IInterActions> m_InterActionsCallbackInterfaces = new List<IInterActions>();
    private readonly InputAction m_inter_Interact;
    public struct InterActions
    {
        private @Player m_Wrapper;
        public InterActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_inter_Interact;
        public InputActionMap Get() { return m_Wrapper.m_inter; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InterActions set) { return set.Get(); }
        public void AddCallbacks(IInterActions instance)
        {
            if (instance == null || m_Wrapper.m_InterActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InterActionsCallbackInterfaces.Add(instance);
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IInterActions instance)
        {
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IInterActions instance)
        {
            if (m_Wrapper.m_InterActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInterActions instance)
        {
            foreach (var item in m_Wrapper.m_InterActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InterActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InterActions @inter => new InterActions(this);

    // Flying car
    private readonly InputActionMap m_Flyingcar;
    private List<IFlyingcarActions> m_FlyingcarActionsCallbackInterfaces = new List<IFlyingcarActions>();
    private readonly InputAction m_Flyingcar_Driving;
    private readonly InputAction m_Flyingcar_Braking;
    public struct FlyingcarActions
    {
        private @Player m_Wrapper;
        public FlyingcarActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Driving => m_Wrapper.m_Flyingcar_Driving;
        public InputAction @Braking => m_Wrapper.m_Flyingcar_Braking;
        public InputActionMap Get() { return m_Wrapper.m_Flyingcar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FlyingcarActions set) { return set.Get(); }
        public void AddCallbacks(IFlyingcarActions instance)
        {
            if (instance == null || m_Wrapper.m_FlyingcarActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FlyingcarActionsCallbackInterfaces.Add(instance);
            @Driving.started += instance.OnDriving;
            @Driving.performed += instance.OnDriving;
            @Driving.canceled += instance.OnDriving;
            @Braking.started += instance.OnBraking;
            @Braking.performed += instance.OnBraking;
            @Braking.canceled += instance.OnBraking;
        }

        private void UnregisterCallbacks(IFlyingcarActions instance)
        {
            @Driving.started -= instance.OnDriving;
            @Driving.performed -= instance.OnDriving;
            @Driving.canceled -= instance.OnDriving;
            @Braking.started -= instance.OnBraking;
            @Braking.performed -= instance.OnBraking;
            @Braking.canceled -= instance.OnBraking;
        }

        public void RemoveCallbacks(IFlyingcarActions instance)
        {
            if (m_Wrapper.m_FlyingcarActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFlyingcarActions instance)
        {
            foreach (var item in m_Wrapper.m_FlyingcarActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FlyingcarActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FlyingcarActions @Flyingcar => new FlyingcarActions(this);
    public interface IInterActions
    {
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface IFlyingcarActions
    {
        void OnDriving(InputAction.CallbackContext context);
        void OnBraking(InputAction.CallbackContext context);
    }
}
